POST http://localhost:3001/api/notes  HTTP/1.1
content-type: application/json

{
    "title": "Hola",
    "body": "Mundo de la vida"
}
###

POST http://localhost:55200/test HTTP/1.1
content-type: application/json

{
    "cname": "weile"
}
###
POST http://localhost:55200/test HTTP/1.1
content-type: application/json
{
    "cname": "weile"
}